# Generated by Django 4.0.5 on 2022-06-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_contactenosmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquiposModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=150)),
                ('fundacion', models.IntegerField()),
                ('presidente', models.CharField(max_length=150)),
                ('dt', models.CharField(max_length=150)),
                ('division', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
